In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv('emails.csv')

In [3]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [5]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [8]:
df['spam'].value_counts()

0    4327
1    1368
Name: spam, dtype: int64

In [9]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [10]:
x=df.text.values

In [11]:
y=df.spam.values

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
xtrain, xtest, ytrain, ytest=train_test_split(x,y, test_size=0.2)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
cv=CountVectorizer()

In [21]:
x_train =cv.fit_transform(xtrain)

In [22]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
#ML algo
from sklearn.naive_bayes import MultinomialNB

In [26]:
model =MultinomialNB()
model.fit(x_train, ytrain)

MultinomialNB()

In [27]:
x_test=cv.transform(xtest)

In [28]:
x_test.toarray()

array([[2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [29]:
model.score(x_test , ytest)

0.9964881474978051

In [31]:
#check email spam or not

emails=['Hey I am badhon parvej. Still now I am learn Machine Learning Language ','Hey you win an iphone x giveway for free pleae do the survey' ]

In [32]:
cv_emails=cv.transform(emails)

In [33]:
model.predict(cv_emails)

array([0, 1], dtype=int64)

In [34]:
# there is 0 means real mail and 1 means spam